---
- name: Check if docker is already installed.
  stat: path=/etc/docker
  register: dockerInstallationStatus

- name: purge old docker packages
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-common
    - container-selinux
    - docker-selinux
    - docker-engine
  when: dockerInstallationStatus.stat.exists == false

- name: install requirements
  yum:
    name: "{{ item }}"
    update_cache: yes
  with_items:
#    - yum-utils
    - device-mapper-persistent-data
    - lvm2
  when: dockerInstallationStatus.stat.exists == false

- name: add docker-engine repository (centos7)
  yum_repository:
    name: docker-engine
    description: Docker Repository
    baseurl: "https://packages.docker.com/{{ dockerVersion }}/yum/repo/main/centos/7"
    gpgkey: https://sks-keyservers.net/pks/lookup?op=get&search=0xee6d536cf7dc86e2d7d56f59a178ac6c6238f52e
    gpgcheck: yes
    file: docker
  when: dockerInstallationStatus.stat.exists == false

- name: install docker-engine
  yum:
    name: docker-engine
    update_cache: yes
  notify:
    - Restart docker-engine
  when: dockerInstallationStatus.stat.exists == false

- name: create docker config dir
  file:
    path: /etc/docker
    state: directory
  when: dockerInstallationStatus.stat.exists == false
