---
# tasks file for kubernetes_master
- name: Install ntp on server
  yum:
   name: ntp
   state: present
  become: true

- name: Install Kubernetes onto the server
  yum:
   name: kubernetes
   state: present
  become: true
  tags: download_kubernetes
  
- name: Install flannel on server
  yum:
   name: flannel
   state: present
  become: true

- name: Copy the apiserver configuration file for etcd server
  template:
    src: "{{ master_api_server_file }}"
    dest: /etc/kubernetes/apiserver
    mode: 0755
  become: true

- name: Copy the kubernetes configuration file from template
  template:
    src: "{{ master_config_file }}"
    dest: /etc/kubernetes/config
  become: true

- name: start the services required
  service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
   - kube-controller-manager
   - kube-apiserver
   - kube-scheduler
   - ntpd
   - flanneld
  become: true
