---

- name: Install flannel and Kubernetes onto the server
  yum:
   name: "{{ item }}"
   state: present
  with_items:
   - flannel
   - kubernetes
  become: true
  tags: download

- name: Copy the flannel configuration file for etcd server
  template:
    src: "{{ flanneld_template }}"
    dest: /etc/sysconfig/flanneld
    mode: 0755
  become: true

- name: Copy the kubernetes configuration file from template
  template:
    src: "{{ kubernetes_config_template }}"
    dest: /etc/kubernetes/config
  become: true

- name: Copy the kubelet file for all the minions
  template:
    src: "{{ minion_kubelet_template }}"
    dest: /etc/kubernetes/kubelet
  become: true

- name: start the services required
  service:
    name: "{{ item }}"
    state: started
    enabled: True
  with_items:
   - kube-proxy
   - kubelet 
   - docker 
   - flanneld

- name: check the ports
  shell: "ip addr | grep flannel | grep inet"
  register: flannel


